export const EXAMPLES_DIRECTORY = './test/examples';

export const ISSUER_PUBLIC_KEY = {
  kty: 'EC',
  x: 'b28d4MwZMjw8-00CG4xfnn9SLMVMM19SlqZpVb_uNtQ',
  y: 'Xv5zWwuoaTgdS6hV43yI6gBwTnjukmFQQnJ_kCxzqk8',
  crv: 'P-256',
  d: 'Ur2bNKuBPOrAaxsRnbSH6hIhmNTxSGXshDSUD1a1y7g',
};

/**
 * Files generated by the sd-jwt-generate python script
 */
export enum Example {
  KB_JWT_HEADER = 'kb_jwt_header.json',
  KB_JWT_PAYLOAD = 'kb_jwt_payload.json',
  KB_JWT = 'kb_jwt_serialized.txt',
  SD_JWT = 'sd_jwt_issuance.txt',
  SD_JWT_JWS = 'sd_jwt_jws_part.txt',
  SD_JWT_PAYLOAD = 'sd_jwt_payload.json',
  SD_JWT_PRESENTATION = 'sd_jwt_presentation.txt',
  USER_CLAIMS = 'user_claims.json',
  VERIFIED_CONTENTS = 'verified_contents.json',
}

export const INVALID_JWT = 'INVALID_JWT_EXAMPLE';
