# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build

on:
  workflow_call:
    outputs:
      cache-key:
        value: ${{ jobs.build.outputs.cache-key }}

jobs:
  build:
    runs-on: ubuntu-latest

    outputs: 
      cache-key: ${{ steps.cache-key.outputs.value }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen # 18
          cache: 'npm'
          check-latest: true
      - run: npm ci
      - id: cache-key
        run: echo "value=dist-${{ hashFiles('src/**/*.ts', 'tsconfig.json', 'tsconfig/*.json', '.github/workflows/*.yml', 'package-lock.json') }}" >> $GITHUB_OUTPUT
      - name: Cache dist
        uses: actions/cache@v3
        id: dist
        with:
          path: dist
          key: ${{ steps.cache-key.outputs.value }}
      - name: Build
        run: npm run build-all
        if: ${{ steps.dist.outputs.cache-hit != 'true' }}
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
      - run: git reset HEAD --hard
