name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  node:
    continue-on-error: ${{ !startsWith(matrix.node-version, 'lts') }}

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - lts/hydrogen # 18
          - current

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        id: node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          check-latest: true
      - run: npm ci
      - name: Run lint:check
        run: npm run lint:check
      - name: Dev Setup
        run: npm run dev:setup
      - name: Dev build
        run: npm run build
      - name: Run Test Suite
        run: npm run test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
